<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
  <!-- Generated via Iro -->
  <dict>
    <key>fileTypes</key>
    <array>
      <string>helix</string>
    </array>
    <key>name</key>
    <string>helix</string>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#main</string>
      </dict>
    </array>
    <key>scopeName</key>
    <string>source.helix</string>
    <key>uuid</key>
    <string></string>
    <key>repository</key>
    <dict>
      <key>main</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>(?:\b)(struct|union)(\s+[_a-zA-Z][_a-zA-Z0-9]*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.helix</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.helix</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(?:\b)(as|put|new)(\s+)([_a-zA-Z][_a-zA-Z0-9]*)</string>
            <key>captures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.other.helix</string>
              </dict>
              <key>2</key>
              <dict>
                <key>name</key>
                <string>keyword.other.helix</string>
              </dict>
              <key>3</key>
              <dict>
                <key>name</key>
                <string>entity.name.type.helix</string>
              </dict>
            </dict>
          </dict>
          <dict>
            <key>match</key>
            <string>(?:\b)(and\sthen|or\selse|and|or|xor)(?:\b)</string>
            <key>name</key>
            <string>keyword.other.helix</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?:\b)(if|then|else|while|do|for|to|until|break|continue|return)(?:\b)</string>
            <key>name</key>
            <string>keyword.control.flow.if.helix</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\bint|void|true|false\b)</string>
            <key>name</key>
            <string>constant.language.helix</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(?:\b)(int|bool|void|var|let|func|as|put|cast|extern)(?:\b)</string>
            <key>name</key>
            <string>keyword.other.helix</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([_a-zA-Z][_a-zA-Z0-9]*)(?=\s*\(.*\))</string>
            <key>name</key>
            <string>variable.function.helix</string>
          </dict>
          <dict>
            <key>match</key>
            <string>([_a-zA-Z][_a-zA-Z0-9]*)</string>
            <key>name</key>
            <string>variable.other.helix</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\&apos;[_a-zA-Z0-9]\&apos;)</string>
            <key>name</key>
            <string>string.quoted.single.helix</string>
          </dict>
          <dict>
            <key>match</key>
            <string>(\/\/.*)</string>
            <key>name</key>
            <string>comment.helix</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>
