<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>trophy</string>
   </array>
  <key>name</key>
  <string>Trophy</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.trophy</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(struct|union)(\s+[a-zA-Z][a-zA-Z0-9]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.trophy</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.trophy</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(as\s+)((?!int|bool|void)[a-zA-Z][a-zA-Z0-9]*)</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.trophy</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>entity.name.type.trophy</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(as\s+)((?=int|bool|void))</string>
          <key>captures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.trophy</string>
            </dict>
            <key>2</key>
            <dict>
              <key>name</key>
              <string>keyword.trophy</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(int|bool|void|var|let|if|then|else|while|do|func|as)</string>
          <key>name</key>
          <string>keyword.trophy</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([a-zA-Z][a-zA-Z0-9]*)(?=\s*\(.*\))</string>
          <key>name</key>
          <string>entity.name.function.trophy</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\/\/.*)</string>
          <key>name</key>
          <string>comment.trophy</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
